# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-29 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.IntegerField(verbose_name='手机'),
        ),
    ]
