# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中间'), ('gj', '高级')], max_length=2, verbose_name='难度'),
        ),
    ]
