# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresourse',
            name='download',
            field=models.FileField(upload_to='course/resource/%Y/%m'),
        ),
    ]
