# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190624_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否为轮播图'),
        ),
    ]
