# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_bannercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/%Y/%m', verbose_name='封面图片'),
        ),
    ]
