# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-16 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 9, 44, 18, 753103)),
        ),
    ]
