# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-19 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190519_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 8, 18, 46, 789491)),
        ),
    ]
