# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190529_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=60, verbose_name='验证码'),
        ),
    ]
