# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190701_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
